name: Update Binance Gold Price

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  update-price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Price from Binance
        run: |
          curl -s "https://fapi.binance.com/fapi/v1/ticker/price?symbol=XAUUSDT" > data.json

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Auto update price" || exit 0
          git push
          
